# Generated by Django 6.1.1 on 2026-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_data_analytics',
            field=models.TextField(blank=True, default='Data cleaning, analysis, Excel, SQL, dashboards, reporting and visualization.', help_text='Description for the Data Analytics card.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_problem_solving',
            field=models.TextField(blank=True, default='I focus on creating practical, useful solutions for real business and data problems.', help_text='Description for the Problem Solving card.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_python',
            field=models.TextField(blank=True, default='Python, Django, automation, database-driven applications and practical software solutions.', help_text='Description for the Python Development card.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_status',
            field=models.BooleanField(default=True, help_text='Enable or disable the public profile.'),
        ),
    ]
