# Generated by Django 6.1.1 on 2026-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current position.', null=True)),
                ('currently_working', models.BooleanField(default=False, help_text='Check this if this is your current position.')),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Describe your main responsibilities and work.')),
                ('technologies', models.CharField(blank=True, help_text='Example: Python, Excel, SQL, Power BI, Django', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['display_order', '-start_date'],
            },
        ),
    ]
