# Generated by Django 6.1.1 on 2026-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon name or CSS class.', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='published',
            field=models.BooleanField(default=True, help_text='Show this skill on the public portfolio.'),
        ),
    ]
